#!/usr/bin/env bash
# Script retrieves domain and subdomain information

get_subdomain_info() {
	local domain=$1
	local subdomain=$2

	if [ -z "$subdomain" ]; then # If zero length
		subdomains=("www" "lb-01" "web-01" "web-02")
	else
		subdomains=("$subdomain")
	fi

	for sub in "${subdomains[@]}"; do
		info=$(dig $sub.$domain | grep "^$sub.$domain" | tr '\t' '\n' | tail -2)
		echo -e "$sub\n$info" | tr '\n' ':' | awk -F: '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
	done
}

get_subdomain_info "$1" "$2"
