#!/usr/bin/env bash
# Installs, configures, and starts the server

# Define the redirect location and target URL
REDIRECT_LOCATION="/redirect_me"
TARGET_URL="https://sketchfab.com/bluepeno/models"

# Define the path to the nginx configuration file
NGINX_CONFIG_FILE="/etc/nginx/sites-available/default"

# Install nginx if it's not already installed
if ! command -v nginx &>/dev/null; then
	apt-get update
	apt-get install -y nginx
fi

mkdir -p /var/www/html
chmod -R 755 /var/www

if grep -q "$REDIRECT_LOCATION" "$NGINX_CONFIG_FILE"; then
	echo "Redirect location already exists in nginx config file."
else
	# Add the redirect location to the config file
	sed -i "/^\s*server_name\s*_;/a \\\n    location $REDIRECT_LOCATION {\n\t\treturn 301 $TARGET_URL;\n    }\n" "$NGINX_CONFIG_FILE"

	# Test the config file and reload nginx if there are no errors
fi
nginx -t && systemctl reload nginx
