#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

NGINX_CONFIG_FILE="/etc/nginx/sites-available/default"
WWW_DIR="/var/www"

# Define the server block as a variable
read -r -d '' SERVER_BLOCK <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    server_name _;

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }    
}
EOF

# Install nginx if it's not already installed
if ! command -v nginx &>/dev/null; then
   apt-get update
   apt-get install -y nginx
fi

# Create the web root directory and set its permissions
mkdir -p "$WWW_DIR/html"
chmod -R 755 "$WWW_DIR"

# Create the custom 404 error page
echo "Ceci n'est pas une page" >"$WWW_DIR/404.html"

# Create the new nginx configuration file
echo "$SERVER_BLOCK" >"$NGINX_CONFIG_FILE"

# Test the new nginx configuration and reload nginx if there are no errors
nginx -t && systemctl reload nginx
