#!/usr/bin/env bash
# Configures a load balancer in lb-01 server

# Install haproxy if it's not already installed
if ! command -v haproxy &>/dev/null; then
	apt update -y && apt install -y haproxy
fi

INIT_FILE="/etc/init.d/haproxy"
INIT_CONFIG='''#!/bin/sh
### BEGIN INIT INFO
# Provides:          haproxy
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: HAProxy
# Description:       HAProxy is a fast and reliable load balancing reverse proxy.
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DAEMON=/usr/sbin/haproxy
NAME=haproxy
DESC=HAProxy
CONFIG="/etc/haproxy/haproxy.cfg"
PIDFILE="/var/run/haproxy.pid"

test -x $DAEMON || exit 0

. /lib/init/vars.sh
. /lib/lsb/init-functions

do_start() {
    $DAEMON -f "$CONFIG" -D -p "$PIDFILE"
}

do_stop() {
    $DAEMON -f "$CONFIG" -D -sf $(cat "$PIDFILE")
}

case "$1" in
    start)
        log_daemon_msg "Starting $DESC" "$NAME"
        do_start
        case "$?" in
            0|1) log_end_msg 0 ;;
            *) log_end_msg 1 ;;
        esac
        ;;
    stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        case "$?" in
            0|1) log_end_msg 0 ;;
            *) log_end_msg 1 ;;
        esac
        ;;
    restart|force-reload)
        log_daemon_msg "Restarting $DESC" "$NAME"
        do_stop
        sleep 1
        do_start
        case "$?" in
            0) log_end_msg 0 ;;
            1) log_end_msg 1 ;;  # Old process is still running
            *) log_end_msg 1 ;;  # Failed to start
        esac
        ;;
    *)
        echo "Usage: \$SCRIPTNAME {start|stop|restart|force-reload}" >&2
        exit 3
        ;;
esac

exit 0
'''

CONFIG_FILE="/etc/haproxy/haproxy.cfg"
CONFIG='''frontend http-in
  bind *:80
  default_backend servers

backend servers
  server web-01 54.162.3.27:80 check
  server web-02 18.235.255.8:80 check
'''

# Create haproxy init script
echo "$INIT_CONFIG" | sudo tee "$INIT_FILE" >/dev/null

# Make the init script executable
sudo chmod +x "$INIT_FILE"

# Enable the init script to start on boot
sudo update-rc.d haproxy defaults

# Create the haproxy config file
echo "$CONFIG" | sudo tee "$CONFIG_FILE" >/dev/null

# Restart haproxy service
sudo service haproxy restart
