#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Kill all processes that are using port 90
# sudo kill $(sudo lsof -t -i :80)
# sudo nginx -t && sudo systemctl restart nginx

rm /etc/nginx/sites-enabled/default
sed -i 's/listen\s*80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
mkdir -p /var/www/html
chmod -R 755 /var/www
echo "Hello world" >/var/www/html/index
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
