#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.

# Kill all processes that are using port 90
kill $(lsof -t -i :80)

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx server
nginx -t && service nginx restartz
