#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
kill "$(pgrep 'nginx' | head -1)"
service nginx start
