#!/usr/bin/env bash
# This script displays Best School 10 times,
#+ but for the 9th iteration, displays Best School and
#+ then Hi on a new line.

LIMIT=10
a=1

while ((a <= LIMIT)); do

	echo "Best School"
	if [[ a -eq 9 ]]; then
		echo "Hi"
	fi
	((a += 1))

done

exit 0
