#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and:
#+ displays 4 and then bad luck from China for the 4th loop iteration
#+ displays 9 and then bad luck from Japan for the 9th loop iteration
#+ displays 17 and then bad luck from Italy for the 17th loop iteration

LIMIT=10
a=1

while ((a <= LIMIT)); do
	case a in
	*)
		if [[ a -eq 4 ]]; then
			echo "bad luck"
		elif [[ a -eq 8 ]]; then
			echo "good luck"
		else
			echo "Best School"
		fi
		;;
	esac

	((a += 1))
done

exit 0
