#!/usr/bin/env bash
# Script changes localhost to resolve to 127.0.0.2

cp /etc/hosts ~/hosts.new
echo "127.0.0.2\t\tlocalhost" >~/hosts.new
echo "8.8.8.8\t\t facebook.com" >>~/hosts.new
cp -f ~/hosts.new >/etc/hosts
