#!/usr/bin/env bash
# Script changes localhost to resolve to 127.0.0.2

cp /etc/hosts ~/hosts.new
echo "127.0.0.2 \t localhost" >~/hosts.new
echo "8.8.8.8 \t facebook.com" >>~/hosts.new
cat ~/hosts.new >/etc/hosts
