#!/usr/bin/env bash
# Script changes localhost to resolve to 127.0.0.2

cp /etc/hosts ~/hosts.new
echo "127.0.0.2\tlocalhost" >~/hosts.new
echo "8.8.8.8\tfacebook.com" >>~/hosts.new
cpy -f ~/hosts.new /etc/hosts
