#!/usr/bin/env bash
# Config nginx to run as the nginx user listening on port 8080.

username="nginx"

if ! command -v haproxy &>/dev/null; then
	apt update -y && apt install -y nginx
fi

# Check if the user already exists

if id "$username" >/dev/null 2>&1; then
	echo "User '$username' already exists."
else # Create the user if it doesn't exist
	adduser --system --no-create-home --disabled-login --group "$username"
	echo "User '$username' created."
fi

# Update Nginx configuration

nginx_config="/etc/nginx/nginx.conf"

# Check if the configuration file exists

if [ -f "$nginx_config" ]; then 
# Remove commented user directive if present
	sed -i "/#*\s*user\s\+\w\+/d" "$nginx_config"

	# Update user directive
	if grep -q "user\s\+\w\+" "$nginx_config"; then
  	  sed -i "s/^user .*/user $username/" "$nginx_config"
	else
	    sed -i "1i user $username;" "$nginx_config"
	fi
	sed -i "s/listen\s*80;/listen 8080;/g" "$nginx_config"
	echo "Nginx configuration updated."
else
	echo "Nginx configuration file not found: $nginx_config"
	exit 1
fi

# Restart Nginx to apply the changes

service nginx restart
