#!/usr/bin/env bash
# Use ssh to connect to my server using the private key `~/.ssh/school`

# Define server details
SERVER_ADDRESS=54.162.3.27
SERVER_USER=ubuntu

PRIVATE_KEY_FILE="$HOME/.ssh/school"

# Using ssh to connect to server
ssh -i "$PRIVATE_KEY_FILE" "$SERVER_USER@$SERVER_ADDRESS"
